[package]
name = "rebuild"
version = "3.0.2"
edition = "2024"
license = "MIT"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.7", features = ["derive", "env"] }
gethostname = "1.1.0"
tempfile = "3.23.0"
thiserror = "2.0.17"
