[package]
name = "command-palette"
version = "3.0.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
thiserror = "2.0.17"

[lints]
workspace = true
