[package]
name = "homepage-back"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1", features = ["http1", "server"] }
tokio = { version = "1", features = ["macros", "net"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["tokio"] }
clap = { version = "4.5.51", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sysinfo = "0.37.2"
serde_with = "3.15.1"
ts-rs = "11.1.0"
reqwest = "0.12.24"
thiserror = "2.0.17"
