#:schema https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

update.method = "never" # Managed by nix

# Don't take us out of the TUI when committing
promptToReturnFromSubprocess = false

# Refuse to open unless we already have a git repo
notARepository = "quit"

[gui]
# Not at all necessary, but fancy
animateExplosion = true
# Fancy icons for languages
nerdFontsVersion = "3"

[git]
# Don't touch HEAD unless I say
autoForwardBranches = "none"

[[git.pagers]]
externalDiffCommand = "difft --color auto --display side-by-side"
