[package]
name = "skyrim-utils"
version = "1.3.1"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
open = "5.2.0"
regex = "1.10.5"
shellexpand = "3.1.0"

[lints]
workspace = true
