# Variables here are provided by Nix
matches:
  - trigger: ":email:"
    replace: "{{email}}"
  - triggers:
      - ":firstname:"
      - ":fname:"
    replace: "{{firstname}}"
  - triggers:
      - ":surname"
      - ":sname:"
    replace: "{{surname}}"
  - trigger: ":today:"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d\t%m\t%y"
